# Generated by Django 3.2.15 on 2022-09-04 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('password', models.CharField(max_length=100)),
                ('ExperienceYear', models.IntegerField()),
                ('speciality', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='storage/resumes')),
                ('identity', models.FileField(upload_to='storage/identity')),
                ('img', models.ImageField(upload_to='storage/img')),
                ('isActive', models.BooleanField(default=False)),
                ('agencyName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agency.agency')),
            ],
        ),
    ]
