# Generated by Django 3.2.15 on 2022-09-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='qualification',
            field=models.FileField(default='storage/qual/dumy.pdf', upload_to='storage/qual'),
        ),
    ]
