# Generated by Django 3.2.15 on 2022-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=12)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('reason', models.TextField()),
                ('message', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
            ],
        ),
    ]
