# Generated by Django 3.2.15 on 2022-09-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='password',
            field=models.CharField(default='test', max_length=100),
        ),
    ]
