# Generated by Django 3.2.15 on 2022-09-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('password', models.CharField(max_length=100)),
                ('noOfHours', models.IntegerField()),
                ('careType', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=12)),
                ('urgency', models.BooleanField()),
                ('religion', models.CharField(max_length=100)),
            ],
        ),
    ]
