# Generated by Django 3.2.15 on 2022-09-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='careType',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='None', max_length=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='noOfHours',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='religion',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='urgency',
            field=models.BooleanField(default=False),
        ),
    ]
