# Generated by Django 3.2.15 on 2022-09-05 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nurse', '0002_nurse_qualification'),
        ('customer', '0002_auto_20220904_1749'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerNurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('nurse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nurse.nurse')),
            ],
        ),
    ]
